sudo: required
services:
  - docker


before_install:
  - docker build -t decaffeinated_dev/docker-react -f Dockerfile.dev .

script:
  - docker run decaffeinated_dev/docker-react npm run test -- --coverage
