sudo: required
services:
  - docker

before_install:
  - docker build -t decaffeinated_dev/docker-react -f Dockerfile.dev .

script:
  - docker run decaffeinated_dev/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-974518479342"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
